name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: heterodox-main
      cancel-in-progress: true
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for client build)
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Build client
        working-directory: client
        run: |
          npm ci
          npm run build

      - name: Ensure target dirs on VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host:     ec2-18-199-237-58.eu-central-1.compute.amazonaws.com
          username: ubuntu
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail
            mkdir -p /home/ubuntu/heterodox/client/dist
            mkdir -p /home/ubuntu/heterodox/server

      - name: Deploy client build
        uses: easingthemes/ssh-deploy@v5.0.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST:      ec2-18-199-237-58.eu-central-1.compute.amazonaws.com
          REMOTE_USER:      ubuntu
          ARGS:             "-avzr --delete"
          SOURCE:           "client/dist/"
          TARGET:           "/home/ubuntu/heterodox/client/dist"

      # --- OPTIONAL: deploy backend code as well ---
      - name: Deploy server code (optional)
        if: ${{ vars.DEPLOY_SERVER == 'true' }}
        uses: easingthemes/ssh-deploy@v5.0.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST:      ec2-18-199-237-58.eu-central-1.compute.amazonaws.com
          REMOTE_USER:      ubuntu
          # prevent secret & DB clobber; keep node_modules deleted remotely
          ARGS: >-
            -avzr --delete
            --exclude='.git'
            --exclude='node_modules'
            --exclude='.env'
            --exclude='asa.db'
          SOURCE:           "server/"
          TARGET:           "/home/ubuntu/heterodox/server"

      - name: Post-deploy (restart backend if deployed; reload Caddy)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host:     ec2-18-199-237-58.eu-central-1.compute.amazonaws.com
          username: ubuntu
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail
            if [ "${{ vars.DEPLOY_SERVER }}" = "true" ]; then
              cd /home/ubuntu/heterodox/server
              # build native deps for the VM's node version
              npm ci --omit=dev
              # restart the correct service name
              sudo systemctl restart heterodox
              # optional: health check upstream
              curl -fsSI http://127.0.0.1:4000/ >/dev/null
            fi
            # Reload Caddy (harmless if unchanged)
            sudo systemctl reload caddy || true
            echo "${{ github.sha }}" > /home/ubuntu/heterodox/.deployed_sha
            date -u > /home/ubuntu/heterodox/.deployed_at
